### ISSUE TITLE
Update to to use new subscriber api launched in v1.18.0?

### ISSUE THREAD

**Issue by ryan-feagin** [pevey/medusa-plugin-ses#5]
I tried upgrading my medusa project to use V1.18 and ran into issues with the SES plugin...

⠙ Initializing plugins
warn:    The subscriber in node_modules/medusa-plugin-ses/dist/subscribers/notification.js is missing a config.
warn:    The subscriber in node_modules/medusa-plugin-ses/dist/subscribers/restock.js is missing a config.
error:   Error starting server
TypeError: Cannot read properties of undefined (reading 'prototype')
    at registerPaymentServiceFromClass (node_modules/@medusajs/medusa/dist/loaders/helpers/plugins.js:9:51)
    at node_modules/@medusajs/medusa/dist/loaders/plugins.js:482:87
    at step (node_modules/@medusajs/medusa/dist/loaders/plugins.js:56:23)
    at Object.next (node_modules/@medusajs/medusa/dist/loaders/plugins.js:37:53)
    at node_modules/@medusajs/medusa/dist/loaders/plugins.js:31:71
    at new Promise (<anonymous>)
    at __awaiter (node_modules/@medusajs/medusa/dist/loaders/plugins.js:27:12)
    at node_modules/@medusajs/medusa/dist/loaders/plugins.js:473:99
    at Array.map (<anonymous>)
    at node_modules/@medusajs/medusa/dist/loaders/plugins.js:473:72

Do you have plans to update the plugin to use the latest subscriber api?

**Comment by raiyansarker** [comment]
I am having the same issue

**Comment by raiyansarker** [comment]
@pevey will there be any update?

**Comment by pevey** [comment]
I no longer use Medusa.  I prefer Vendure.

**Comment by jacksenior** [comment]
@pevey I'm going to fork this and do the upgrade for my site. I am happy to take over here and release version 2.0 for the Medusa community if not I'll likely publish my fork and credit you for the OG.

**Comment by pevey** [comment]
Now updated for Medusa v2, closing this issue
